[env]
TERM = "alacritty"

[window]
decorations = "Full"

[font]
size = 30.0

[font.normal]
family = "MonaspiceNe Nerd Font"

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = '#64748b'   # slate.500
blue = '#7dd3fc'    # sky.300
cyan = '#a5f3fc'    # cyan.200
green = '#5eead4'   # teal.300
magenta = '#f9a8d4' # pink.300
red = '#fb7185'     # red.400
white = '#f1f5f9'   # slate.100
yellow = '#fde047'  # yellow.300

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.footer_bar]
background = "#0f172a"
foreground = "#f8fafc"

[colors.hints.end]
background = "#0f172a"
foreground = "#38bdf8"

[colors.hints.start]
background = "#38bdf8"
foreground = "#f8fafc"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black = '#0f172a'   # slate.900
blue = '#38bdf8'    # sky.400
cyan = '#67e8f9'    # cyan.300
green = '#2dd4bf'   # teal.400
magenta = '#f472b6' # pink.400
red = '#f43f5e'     # rose.500
white = '#cbd5e1'   # slate.300
yellow = '#facc15'  # yellow.400

[colors.primary]
background = "#0f172a"
bright_foreground = "#ffffff"
foreground = "#f8fafc"

[colors.search.focused_match]
background = "#67e8f9" # cyan.300
foreground = "#0f172a" # slate.900

[colors.search.matches]
background = "#164e63" # cyan.900
foreground = "#f8fafc" # slate.100

[colors.selection]
background = "#164e63"  # cyan.900
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[shell]
args = ["--login", "--command", "exec tmux"]
program = "/opt/homebrew/bin/fish"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Return"
mode = "~Search"
mods = "Control"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "T"
mods = "Command"
